export const actions = {
  //clients
  GET_CLIENTS: "GET_CLIENTS",
  ADD_CLIENT: "ADD_CLIENT",
  CLIENTS_ERROR: "CLIENTS_ERROR",
  GET_DOMESTIC_CLIENTS: "GET_DOMESTIC_CLIENTS",
  UPDATED_CLIENTS: "UPDATED_CLIENTS",
  GET_LAST_ID: "GET_LAST_ID",
  SEARCH_CLIENTS: "SEARCH_CLIENTS",

  //invoices
  ADD_INVOICE: "ADD_INVOICE",
  GET_INVOICES: "GET_INVOICES",
  INVOICES_ERROR: "INVOICES_ERROR",
  GET_PAID_INVOICES: "GET_PAID_INVOICES",
  GET_UNPAID_INVOICES: "GET_UNPAID_INVOICES",
  GET_INVOICES_DUE_THIS_MONTH: "GET_INVOICES_DUE_THIS_MONTH",
  SEARCH_INVOICES: "SEARCH_INVOICES",

  //client details
  SET_CLIENT: "SET_CLIENT",
  GET_CURR_CLIENT: "GET_CURR_CLIENT",
  GET_PAID_INV: "GET_PAID_INV",
  GET_UNPAID_INV: "GET_UNPAID_INV",
  GET_ALL_INVOICES: "GET_ALL_INVOICES",
  SEARCH_CLIENT_DETAILS: "SEARCH_CLIENT_DETAILS",

  //users
  GET_USERS: "GET_USERS",
  USERS_ERROR: "USERS_ERROR",

  //userinfo
  USER_INFO: "USER_INFO",

  //todos
  ADD_TODO: "ADD_TODO",
  GET_TODOS: "GET_TODOS",
  DELETE_TODO: "DELETE_TODO",
  UPDATE_TODO: "UPDATE_TODO",
  TODO_ERROR: "TODO_ERROR",
};
